#spring.application.name=analysis
#spring.profiles.active=prod
#spring.cloud.config.label=main
#
#spring.config.import=configserver:http://localhost:9065
#
#spring.cloud.config.username=psc
#spring.cloud.config.password=psc123$
#
#management.endpoints.web.exposure.include=health,info,refresh
#endpoints.env.keys-to-sanitize=true
#spring.cloud.config.import-check.enabled=false
#
#logging.level.root=INFO



spring.application.name=flashcard
# Server port
server.port=8081
# Scorer service URL

spring.datasource.url=jdbc:mysql://devenochmysql:3306/psc?user=psc&password=psc123$&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
spring.datasource.username=psc
spring.datasource.password=psc123$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
